In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
import random
import librosa
import sklearn
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

In [2]:
DATADIR = ""
CATEGORIES = ["Segmented_Laugh", "Segmented_NonLaugh"]

In [3]:
a = np.array([[1, 2, 3, 4], [10, 20, 30, 40], [100, 200, 300, 400]], np.int32)
a[[0,2],:]

array([[  1,   2,   3,   4],
       [100, 200, 300, 400]], dtype=int32)

# Loading Data

In [4]:
#For choosing MORE THAN ONE particular MFCC'S
n_mfcc = 3
training_data = []
def create_training_data():
    count=0
    error_count = 0
    #Enter time in seconds
    t_window = 1
    t_frame = 0.025
    t_shift = 0.01
    n_mfccs = n_mfcc
    laugh_counter = 0
    nonlaugh_counter = 0
    for category in CATEGORIES:
        path = os.path.join(DATADIR, category) 
        class_num = CATEGORIES.index(category)
        print('New Folder')
        for aud in os.listdir(path):
            if aud == '.DS_Store':
                continue
            
            aud_array , sr = librosa.load(os.path.join(path,aud), sr=None)
            count+=1

            mfccs = []
            
            try:
                mfcc = (librosa.feature.mfcc(aud_array, sr=sr,  n_mfcc=20,  win_length = int(sr*t_frame), hop_length = int(sr*t_shift))) 
                mfcc_temp = mfcc[[0,2,6],:]
                #mfcc_delta = librosa.feature.delta(mfcc_temp)
                
                mean_mfccs = np.mean(np.asarray(mfcc_temp),axis = 1)
                var_mfccs = np.var(np.asarray(mfcc_temp), axis = 1)
                #std_deltamfccs = np.std(np.asarray(mfcc_delta), axis = 1)
                
                mfccs.append(mean_mfccs)
                mfccs.append(var_mfccs)
                #mfccs.append(std_deltamfccs)
                mfccs = np.asarray(mfccs).reshape(n_mfccs*2,1)
                training_data.append([mfccs.reshape(-1,1), class_num])
                if category == 'Segmented_Laugh':
                    laugh_counter +=1
                else:
                    nonlaugh_counter += 1

            except ValueError:
                print("Oops!  That was no valid number.  Try again...")
        
    print(laugh_counter, nonlaugh_counter)

In [9]:
#For choosing ONE particular MFCC'S
n_mfcc = 1
training_data = []
def create_training_data():
    count=0
    error_count = 0
    #Enter time in seconds
    t_window = 1
    t_frame = 0.025
    t_shift = 0.01
    n_mfccs = n_mfcc
    laugh_counter = 0
    nonlaugh_counter = 0
    for category in CATEGORIES:
        path = os.path.join(DATADIR, category) 
        class_num = CATEGORIES.index(category)
        print('New Folder')
        for aud in os.listdir(path):
            if aud == '.DS_Store':
                continue
            
            aud_array , sr = librosa.load(os.path.join(path,aud), sr=None)
            count+=1

            mfccs = []
            
            try:
                mfcc = (librosa.feature.mfcc(aud_array, sr=sr,  n_mfcc=20,  win_length = int(sr*t_frame), hop_length = int(sr*t_shift))) 
                mfcc_temp = mfcc[0,:]
                #mfcc_delta = librosa.feature.delta(mfcc_temp)
                
                mean_mfccs = np.mean(np.asarray(mfcc_temp),axis = 0)
                var_mfccs = np.var(np.asarray(mfcc_temp), axis = 0)
                #std_deltamfccs = np.std(np.asarray(mfcc_delta), axis = 1)
                
                mfccs.append(mean_mfccs)
                mfccs.append(var_mfccs)
                #mfccs.append(std_deltamfccs)
                mfccs = np.asarray(mfccs).reshape(n_mfccs*2,1)
                training_data.append([mfccs.reshape(-1,1), class_num])
                if category == 'Segmented_Laugh':
                    laugh_counter +=1
                else:
                    nonlaugh_counter += 1

            except ValueError:
                print("Oops!  That was no valid number.  Try again...")
        
    print(laugh_counter, nonlaugh_counter)

In [8]:
#For choosing ONE particular MFCC'S
n_mfcc = 1
training_data = []
def create_training_data():
    count=0
    error_count = 0
    #Enter time in seconds
    t_window = 1
    t_frame = 0.025
    t_shift = 0.01
    n_mfccs = n_mfcc
    laugh_counter = 0
    nonlaugh_counter = 0
    for category in CATEGORIES:
        path = os.path.join(DATADIR, category) 
        class_num = CATEGORIES.index(category)
        print('New Folder')
        for aud in os.listdir(path):
            if aud == '.DS_Store':
                continue
            
            aud_array , sr = librosa.load(os.path.join(path,aud), sr=None)
            count+=1

            mfccs = []
            
            try:
                mfcc = (librosa.feature.mfcc(aud_array, sr=sr,  n_mfcc=20,  win_length = int(sr*t_frame), hop_length = int(sr*t_shift))) 
                mfcc_temp = mfcc[0,:]
                mfcc_delta = librosa.feature.delta(mfcc_temp)
                
                #mean_mfccs = np.mean(np.asarray(mfcc_temp),axis = 0)
                #var_mfccs = np.var(np.asarray(mfcc_temp), axis = 0)
                mean_deltamfccs = np.std(np.asarray(mfcc_delta), axis = 0)
                std_deltamfccs = np.std(np.asarray(mfcc_delta), axis = 0)
                
                #mfccs.append(mean_mfccs)
                #mfccs.append(var_mfccs)
                mfccs.append(mean_deltamfccs)
                mfccs.append(std_deltamfccs)
                mfccs = np.asarray(mfccs).reshape(n_mfccs*2,1)
                training_data.append([mfccs.reshape(-1,1), class_num])
                if category == 'Segmented_Laugh':
                    laugh_counter +=1
                else:
                    nonlaugh_counter += 1

            except ValueError:
                print("Oops!  That was no valid number.  Try again...")
        
    print(laugh_counter, nonlaugh_counter)

In [9]:
create_training_data()
data = np.array(training_data)

New Folder
New Folder
Oops!  That was no valid number.  Try again...
Oops!  That was no valid number.  Try again...
Oops!  That was no valid number.  Try again...
Oops!  That was no valid number.  Try again...
Oops!  That was no valid number.  Try again...
Oops!  That was no valid number.  Try again...
Oops!  That was no valid number.  Try again...
Oops!  That was no valid number.  Try again...
Oops!  That was no valid number.  Try again...
Oops!  That was no valid number.  Try again...
Oops!  That was no valid number.  Try again...
Oops!  That was no valid number.  Try again...
Oops!  That was no valid number.  Try again...
Oops!  That was no valid number.  Try again...
Oops!  That was no valid number.  Try again...
Oops!  That was no valid number.  Try again...
Oops!  That was no valid number.  Try again...
Oops!  That was no valid number.  Try again...
Oops!  That was no valid number.  Try again...
Oops!  That was no valid number.  Try again...
Oops!  That was no valid number.  Try 

# Shuffling data

In [10]:
# mfcc array | class
random.shuffle(training_data)

In [11]:
# each row has 96 features(mfcc matrix)
data[0,0].shape

(2, 1)

In [12]:
X = []
Y = []
for features, label in training_data:
    X.append(features)
    Y.append(label)

    
X = np.array(X).reshape(-1,n_mfcc*2)
#-1 corresponds to how many features we have
Y = np.array(Y)
#X = X/250
#print(X.shape)
#print(Y)
X.shape

(3354, 2)

# Data split for training

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, 
                                                    test_size=0.1, 
                                                    random_state=4)

In [14]:
y_test.shape

(336,)

# Training SVM 

In [15]:
classifier = svm.SVC(kernel='linear')
classifier.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [16]:
y_pred = classifier.predict(X_test)
#tn, fp, fn, tp = confusion_matrix(y_test,y_pred, labels=[0,1])
print(confusion_matrix(y_test,y_pred, labels=[0,1]))
print(classification_report(y_test,y_pred))

[[140  33]
 [ 89  74]]
              precision    recall  f1-score   support

           0       0.61      0.81      0.70       173
           1       0.69      0.45      0.55       163

    accuracy                           0.64       336
   macro avg       0.65      0.63      0.62       336
weighted avg       0.65      0.64      0.62       336



In [194]:
y_pred = classifier.predict(X_test)
#tn, fp, fn, tp = confusion_matrix(y_test,y_pred, labels=[0,1])
print(confusion_matrix(y_test,y_pred, labels=[0,1]))
print(classificat0ion_report(y_test,y_pred))

[[ 53 122]
 [ 28 133]]


NameError: name 'classificat0ion_report' is not defined

# Testing it against test dataset 

In [16]:
counter = 0
correct = 0
total = 0
chosenclass = 0
for y in y_test:
    if y == chosenclass:
        total += 1
        #if y_pred[counter]== y:
         #   correct += 1
    counter += 1
    

In [17]:
correct

0

In [18]:
total

175

In [17]:
counter

336